-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 23:47:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aluno` ;

CREATE TABLE IF NOT EXISTS `Aluno` (
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Sexo` CHAR NULL,
  `DataNascimento` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Area` ;

CREATE TABLE IF NOT EXISTS `Area` (
  `Sigla` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `SuperArea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Area_Area`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Area_Area_idx` ON `Area` (`SuperArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Curso` ;

CREATE TABLE IF NOT EXISTS `Curso` (
  `Sigla` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` TIME NULL,
  `Custo` FLOAT NULL,
  `Area_Sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`, `Area_Sigla`),
  CONSTRAINT `fk_Curso_Area1`
    FOREIGN KEY (`Area_Sigla`)
    REFERENCES `Area` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_Area1_idx` ON `Curso` (`Area_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matricula` ;

CREATE TABLE IF NOT EXISTS `Matricula` (
  `Curso` VARCHAR(45) NOT NULL,
  `Data` DATE NULL,
  `Pago` TINYINT NULL,
  `Matriculacol` VARCHAR(45) NULL,
  `Curso_Sigla` VARCHAR(45) NOT NULL,
  `Curso_Area_Sigla` VARCHAR(45) NOT NULL,
  `Aluno_CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Curso`, `Curso_Sigla`, `Curso_Area_Sigla`),
  CONSTRAINT `fk_Matricula_Curso1`
    FOREIGN KEY (`Curso_Sigla` , `Curso_Area_Sigla`)
    REFERENCES `Curso` (`Sigla` , `Area_Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Aluno1`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Matricula_Curso1_idx` ON `Matricula` (`Curso_Sigla` ASC, `Curso_Area_Sigla` ASC) VISIBLE;

CREATE INDEX `fk_Matricula_Aluno1_idx` ON `Matricula` (`Aluno_CPF` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Modulo` ;

CREATE TABLE IF NOT EXISTS `Modulo` (
  `Sigla` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Curso` VARCHAR(45) NULL,
  `Topico_Sigla` VARCHAR(45) NOT NULL,
  `Curso_Sigla` VARCHAR(45) NOT NULL,
  `Curso_Area_Sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_Modulo_Topico1`
    FOREIGN KEY (`Topico_Sigla`)
    REFERENCES `Topico` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modulo_Curso1`
    FOREIGN KEY (`Curso_Sigla` , `Curso_Area_Sigla`)
    REFERENCES `Curso` (`Sigla` , `Area_Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Modulo_Topico1_idx` ON `Modulo` (`Topico_Sigla` ASC) VISIBLE;

CREATE INDEX `fk_Modulo_Curso1_idx` ON `Modulo` (`Curso_Sigla` ASC, `Curso_Area_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Professor` ;

CREATE TABLE IF NOT EXISTS `Professor` (
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Curso_Sigla` VARCHAR(45) NOT NULL,
  `Curso_Area_Sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`, `Curso_Sigla`, `Curso_Area_Sigla`),
  CONSTRAINT `fk_Professor_Curso1`
    FOREIGN KEY (`Curso_Sigla` , `Curso_Area_Sigla`)
    REFERENCES `Curso` (`Sigla` , `Area_Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Professor_Curso1_idx` ON `Professor` (`Curso_Sigla` ASC, `Curso_Area_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Topico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Topico` ;

CREATE TABLE IF NOT EXISTS `Topico` (
  `Sigla` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` TIME NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
